# nodejs
# vue-cli
version: '3'
services:
  node:
    build: .
    container_name: node 
    volumes:
      - ./admin:/usr/app/
      - /usr/app/node_modules # node_modulesは、コンテナ側のものを利用する
    ports:
      - "8080:8080"
    tty: true
  nginx:
    image: nginx:1.15.3
    container_name: nginx
    volumes:
      - ./admin/dist:/var/app/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    tty: true
